openapi: 3.0.0
servers:
  - description: Dynanmo API
    url: 'https://api.dynamoapi.com'
  - description: Dynamo Test API
    url: 'https://dev.dynamoapi.com'
info:
  version: 1.0.0
  title: Dynamo API
  description: Dynamo API documentation for integrations
tags:
  - name: Pricing
    description: Get pricing for Dynamo products
paths:
  /pricing/breakdown:
    post:
      tags:
        - Pricing
      summary: Breakdown prices
      description: 'Fetches breakdown prices for vehicle or personal cover.'
      parameters:
        - name: Authorization
          in: header
          description: 'The `Authorization` header is used to authenticate with the API using your API key. Value is of the format `Token YOUR_API_KEY`.'
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  object:
                    type: string
                    example: list
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/BreakdownPricingResponse'
              examples:
                European Vehicle Cover:
                  value:
                    object: list
                    data:
                      - id: 1
                        deeplink: 'https://myaccount.dynamo.com/quote/breakdown/d668f522-4b86-4470-bf4d-9173e802ef4d'
                        name: Gold
                        price: 59.30
                        excess: 0.00
                        vehicle: true
                        european: true
                        onward_journey: true
                        home_start: true
                        misfuelling: true
                      - id: 2
                        deeplink: 'https://myaccount.dynamo.com/quote/breakdown/ca4b0387-bb70-47d4-baf7-f8de4da343f5'
                        name: Gold XS
                        price: 53.08
                        excess: 25.00
                        vehicle: true
                        european: true
                        onward_journey: true
                        home_start: true
                        misfuelling: true
                Personal Cover:
                  value:
                    object: list
                    data:
                      - id: 1
                        deeplink: 'https://myaccount.dynamo.com/quote/breakdown/0a72b2b1-9e51-4bbe-93a6-b83e1f993d3a'
                        name: Personal Breakdown
                        price: 79.81
                        excess: 0.00
                        personal: true
                        national: true
                        onward_journey: true
                        home_start: true
                        misfuelling: true
                      - id: 2
                        deeplink: 'https://myaccount.dynamo.com/quote/breakdown/beff5081-8d14-419a-babb-0d28067cc915'
                        name: Personal Breakdown XS
                        price: 66.96
                        excess: 25.00
                        personal: true
                        national: true
                        onward_journey: true
                        home_start: true
                        misfuelling: true
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InsufficientPermissionsResponse'

      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BreakdownPricingRequest'

  /pricing/gadget:
    post:
      tags:
        - Pricing
      summary: Gadget prices
      description: 'Fetches gadget prices.'
      parameters:
        - name: Authorization
          in: header
          description: 'The `Authorization` header is used to authenticate with the API using your API key. Value is of the format `Token YOUR_API_KEY`.'
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  object:
                    type: string
                    example: list
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/GadgetPricingResponse'
              examples:
                Gold:
                  value:
                    object: list
                    data:
                      - id: 1
                        deeplink: 'https://myaccount.dynamo.com/quote/gadget/d668f522-4b86-4470-bf4d-9173e802ef4d'
                        name: Gold
                        annual_price: 59.30
                        monthly_price: 5.93
                        # excess_min_accidental_damage: 0.00
                        # excess_max_accidental_damage: 0.00
                        # excess_min_breakdown: 0.00
                        # excess_max_breakdown: 0.00
                        # excess_min_theft: 0.00
                        # excess_max_theft: 0.00
                        excess: 0.00
                        accidental_damage_cover: true
                        theft_cover: true
                        loss_cover: true
                        instant_cover: true
                        breakdown_cover: true
                        
                      - id: 2
                        deeplink: 'https://myaccount.dynamo.com/quote/gadget/ca4b0387-bb70-47d4-baf7-f8de4da343f5'
                        name: Gold XS
                        annual_price: 53.08
                        monthly_price: 5.31
                        # excess_min_accidental_damage: 25.00
                        # excess_max_accidental_damage: 25.00
                        # excess_min_breakdown: 25.00
                        # excess_max_breakdown: 25.00
                        # excess_min_theft: 25.00
                        # excess_max_theft: 25.00
                        excess: 25.00
                        accidental_damage_cover: true
                        theft_cover: true
                        loss_cover: true
                        instant_cover: true
                        breakdown_cover: true
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InsufficientPermissionsResponse'

      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GadgetPricingRequest'

components:
  schemas:
    # Generic error responses
    InsufficientPermissionsResponse:
      type: 'object'
      properties:
        error:
          type: object
          properties:
            code:
              type: string
              example: INSUFFICIENT_PERMISSIONS
            message:
              type: string
              example: Invalid API Integration Token
    BadRequestResponse:
      type: 'object'
      properties:
        error:
          type: object
          properties:
            code:
              type: string
              example: BAD_REQUEST
            message:
              type: string
              example: Not a valid request
            serializer_error:
              type: object
              properties:
                field:
                  type: string
                  example: This field is required
  
    # Breakdown pricing schemas
    Vehicle:
      type: 'object'
      required:
        - vehicle_age
        - reg_number
        - reg_date
        - manufacture_date
        - make
        - model
      properties:
        vehicle_type:
          type: string
          example: CAR
          description: Vehicle type - i.e., `CAR`, `VAN`, `BIKE`. Defaults to `CAR`.
        vehicle_age:
          type: integer
          example: 2
          description: Vehicle age in years. This field, `reg_date` or `manufacture_date` is required.
        reg_number:
          type: string
          example: BT69YVC
          description: Vehicle registration number.
        reg_date:
          type: string
          example: '2019-12-01'
          description: Vehicle registration date in the format `YYYY-MM-DD`. This field, `manufacture_date` or `vehicle_age` is required.
        manufacture_date:
          type: string
          example: '2019-12-01'
          description: Vehicle manufacture date in the format `YYYY-MM-DD`. This field, `reg_date` or `vehicle_age` is required. This field is preferred.
        make:
          type: string
          example: VOLKSWAGEN
          description: Vehicle make. Required.
        model:
          type: string
          example: GOLF
          description: Vehicle model. Required.
        engine_size:
          type: integer
          example: 1498
          description: Vehicle engine size.
        fuel_type:
          type: string
          example: PETROL
          description: Vehicle fuel type.
        transmission_type:
          type: string
          example: AUTOMATIC
          description: Vehicle transmission type.
        colour:
          type: string
          example: GREY
          description: Vehicle colour.
        doors:
          type: integer
          example: 5
          description: Number of vehicle doors.
    BreakdownPricingRequest:
      type: 'object'
      required:
        - source
        - first_name
        - last_name
        - email
      properties:
        source:
          type: string
          example: CTM
          description: 'Source/Aggregator shortcode - i.e., `CTM` (Compare the Market), `QZ` (QuoteZone) etc.'
        affiliate_quote_id:
          type: string
          description: Affiliate Quote ID Reference.

        # Policy details 
        start_date:
          type: string
          default: today
          example: '2025-01-01'
          description: Policy start date in the format 'YYYY-MM-DD'.
        end_date:
          type: string
          example: '2026-01-01'
          description: Policy end date in the format `YYYY-MM-DD`. When set, only single trip cover is returned.
        # term:
        #   type: integer
        #   default: 12
        #   description: Policy term in months

        # Customer details
        email:
          type: string
          example: johndoe@email.com
          description: Customers email address.
        title:
          type: string
          example: MR
          description: 'Customer title - e.g., `MR`, `MRS`, `MISS`, `MS`, `DR`, `MX`.'
        first_name:
          type: string
          example: John
          description: Customers first name.
        last_name:
          type: string
          example: Doe
          description: Customers last name.
        datebirth:
          type: string
          example: '1987-10-07'
          description: Customers date of birth in the format `YYYY-MM-DD`.
        phone_number:
          type: string
          example: '07780510828'
          description: Customers phone number.
        address1:
          type: string
          example: 'The Business Centre, Cardiff House'
          description: Customers first line of address. When set, `city` and `postcode` is also required. 
        address2:
          type: string
          example: 'Priority Business Park'
          description: Customers second line of address. If no second line, set to null or omit field from request body. When set, `address1`, `city` and `postcode` is also required.
        city:
          type: string
          example: 'BARRY'
          description: Customers city. When set, `address1` and `postcode` is also required.
        postcode:
          type: string
          example: 'CF632AW'
          description: Customers postcode. When set, `address1` and `city` is also required.

        # Product flags
        personal:
          type: boolean
          example: false
          description: Set to `true` for personal breakdown prices.
        vehicle:
          type: boolean
          example: true
          description: Set to `true` for vehicle breakdown prices. When set to `true`, `vehicles` should contain at least one vehicle.
        local:
          type: boolean
          example: true
          description: Set to `true` for breakdown prices with local cover.
        national:
          type: boolean
          example: true
          description: Set to `true` for breakdown prices with national cover.
        european:
          type: boolean
          example: true
          description: Set to `true` for breakdown prices with European cover.
        onward_journey:
          type: boolean
          example: true
          description: Set to `true` for breakdown prices that include onward journey.
        home_start:
          type: boolean
          example: true
          description: Set to `true` for breakdown prices that include home start.
        misfuelling:
          type: boolean
          example: true
          description: Set to `true` for breakdown prices that include misfuelling.

        # Vehicles
        vehicles:
          type: array
          description: "List of vehicles. `NOTE - We only support 1 vehicle per request at the moment.`"
          items:
            $ref: '#/components/schemas/Vehicle'
        vehicle_type:
          type: string
          example: CAR
          description: Vehicle type - i.e., `CAR`, `VAN`, `BIKE`. Defaults to `CAR`. DEPRECATED - Use `vehicles` instead.
          deprecated: true
        vehicle_age:
          type: integer
          example: 2
          description: Vehicle age in years. This field, `reg_date` or `manufacture_date` is required when `vehicle` is set to `true`. DEPRECATED - Use `vehicles` instead.
          deprecated: true
        reg_number:
          type: string
          example: BT69YVC
          description: Vehicle registration number. Required when `vehicle` is set to `true`. DEPRECATED - Use `vehicles` instead.
          deprecated: true
        reg_date:
          type: string
          example: '2019-12-01'
          description: Vehicle registration date in the format `YYYY-MM-DD`. This field, `manufacture_date` or `vehicle_age` is required when `vehicle` is set to `true`. DEPRECATED - Use `vehicles` instead.
          deprecated: true
        manufacture_date:
          type: string
          example: '2019-12-01'
          description: Vehicle manufacture date in the format `YYYY-MM-DD`. This field, `reg_date` or `vehicle_age` is required when `vehicle` is set to `true`. This field is preferred. DEPRECATED - Use `vehicles` instead.
          deprecated: true
        make:
          type: string
          example: VOLKSWAGEN
          description: Vehicle make. Required when `vehicle` is set to `true`. DEPRECATED - Use `vehicles` instead.
          deprecated: true
        model:
          type: string
          example: GOLF
          description: Vehicle model. Required when `vehicle` is set to `true`. DEPRECATED - Use `vehicles` instead.
          deprecated: true
        engine_size:
          type: integer
          example: 1498
          description: Vehicle engine size. DEPRECATED - Use `vehicles` instead.
          deprecated: true
        fuel_type:
          type: string
          example: PETROL
          description: Vehicle fuel type. DEPRECATED - Use `vehicles` instead.
          deprecated: true
        transmission_type:
          type: string
          example: AUTOMATIC
          description: Vehicle transmission type. DEPRECATED - Use `vehicles` instead.
          deprecated: true
        colour:
          type: string
          example: GREY
          description: Vehicle colour. DEPRECATED - Use `vehicles` instead.
          deprecated: true
        doors:
          type: integer
          example: 5
          description: Number of vehicle doors. DEPRECATED - Use `vehicles` instead.
          deprecated: true

    BreakdownPricingResponse:
      type: 'object'
      properties:
        deeplink:
          type: string
          example: 'https://myaccount.dynamocover.com/quote/breakdown/d668f522-4b86-4470-bf4d-9173e802ef4d'
        name:
          type: string
          example: Gold
        price:
          type: number
          example: 30.00
        excess:
          type: number
          example: 15.00
        personal:
          type: boolean
          example: false
        vehicle:
          type: boolean
          example: true
        local:
          type: boolean
          example: false
        national:
          type: boolean
          example: true
        european:
          type: boolean
          example: false
        onward_journey:
          type: boolean
          example: true
        home_start:
          type: boolean
          example: true
        misfuelling:
          type: boolean
          example: true
  
    # Gadget pricing schemas
    Gadget:
      type: 'object'
      required:
        - id
        - purchase_date
        - loss_cover
        - purchase_condition
      properties:
        id:
          type: integer
          example: 1
          description: Gadget ID from our gadget list. Ask your contact at Dynamo for the latest list.
        purchase_date:
          type: string
          example: '2025-01-01'
          description: Gadget purchase date in the format `YYYY-MM-DD`.
        loss_cover:
          type: boolean
          example: true
          description: Set to `true` for loss cover.
        purchase_condition:
          type: string
          example: NEW
          description: Gadget purchase condition - i.e., `NEW`, `REFURBISHED`, `SECOND_HAND`.
    GadgetPricingRequest:
      type: 'object'
      required:
        - source
        - first_name
        - last_name
        - email
        - gadgets
      properties:
        source:
          type: string
          example: CTM
          description: 'Source/Aggregator shortcode - i.e., `CTM` (Compare the Market), `QZ` (QuoteZone) etc.'
        affiliate_quote_id:
          type: string
          description: Affiliate Quote ID Reference.

        # Policy details
        start_date:
          type: string
          default: today
          example: '2025-01-01'
          description: Policy start date in the format 'YYYY-MM-DD'.
        # end_date:
        #   type: string
        #   example: '2026-01-01'
        #   description: Policy end date in the format `YYYY-MM-DD`.
        # term:
        #   type: integer
        #   default: 12
        #   description: Policy term in months

        # Customer details
        email:
          type: string
          example: johndoe@email.com
          description: Customers email address.
        title:
          type: string
          example: MR
          description: 'Customer title - e.g., `MR`, `MRS`, `MISS`, `MS`, `DR`, `MX`.'
        first_name:
          type: string
          example: John
          description: Customers first name.
        last_name:
          type: string
          example: Doe
          description: Customers last name.
        datebirth:
          type: string
          example: '1987-10-07'
          description: Customers date of birth in the format `YYYY-MM-DD`.
        phone_number:
          type: string
          example: '07780510828'
          description: Customers phone number.
        address1:
          type: string
          example: 'The Business Centre, Cardiff House'
          description: Customers first line of address. When set, `city` and `postcode` is also required. 
        address2:
          type: string
          example: 'Priority Business Park'
          description: Customers second line of address. If no second line, set to null or omit field from request body. When set, `address1`, `city` and `postcode` is also required.
        city:
          type: string
          example: 'BARRY'
          description: Customers city. When set, `address1` and `postcode` is also required.
        postcode:
          type: string
          example: 'CF632AW'
          description: Customers postcode. When set, `address1` and `city` is also required.

        # Product flags
        accidental_damage_cover:
          type: boolean
          example: true
          description: Set to `true` for accidental damage cover.
        theft_cover:
          type: boolean
          example: true
          description: Set to `true` for theft cover.
        instant_cover:
          type: boolean
          example: true
          description: Set to `true` for instant cover.
        breakdown_cover:
          type: boolean
          example: true
          description: Set to `true` for mechanical breakdown cover.

        # Gadgets
        gadgets:
          type: array
          description: "List of gadgets. `NOTE - We only support 1 gadget per request at the moment.`"
          items:
            $ref: '#/components/schemas/Gadget'
  
    GadgetPricingResponse:
      type: 'object'
      properties:
        deeplink:
          type: string
          example: 'https://myaccount.dynamocover.com/quote/gadget/d668f522-4b86-4470-bf4d-9173e802ef4d'
        name:
          type: string
          example: Gold XS
        annual_price:
          type: number
          example: 53.08
        monthly_price:
          type: number
          example: 5.31
        # excess_min_accidental_damage:
        #   type: number
        #   example: 25.00
        # excess_max_accidental_damage:
        #   type: number
        #   example: 25.00
        # excess_min_breakdown:
        #   type: number
        #   example: 25.00
        # excess_max_breakdown:
        #   type: number
        #   example: 25.00
        # excess_min_theft:
        #   type: number
        #   example: 25.00
        # excess_max_theft:
        #   type: number
        #   example: 25.00
        excess:
          type: number
          example: 25.00
        accidental_damage_cover:
          type: boolean
          example: true
        theft_cover:
          type: boolean
          example: true
        loss_cover:
          type: boolean
          example: true
        instant_cover:
          type: boolean
          example: true
        breakdown_cover:
          type: boolean
          example: true
